// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYgBAI42O3sfrWDwT8YhULx25SoyVyq68',
    appId: '1:591916390428:web:fe86cb1bb818cfb3c3e7d9',
    messagingSenderId: '591916390428',
    projectId: 'financeapp-922c4',
    authDomain: 'financeapp-922c4.firebaseapp.com',
    storageBucket: 'financeapp-922c4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDspKopCf_723x9CHBwqgCUDWiZL4bhN90',
    appId: '1:591916390428:android:8f5664f674c2bbd4c3e7d9',
    messagingSenderId: '591916390428',
    projectId: 'financeapp-922c4',
    storageBucket: 'financeapp-922c4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBF__m92jpQ6O2ln-ohMtBVufjFP7M2xDQ',
    appId: '1:591916390428:ios:2f4ca12b84eb215cc3e7d9',
    messagingSenderId: '591916390428',
    projectId: 'financeapp-922c4',
    storageBucket: 'financeapp-922c4.appspot.com',
    iosClientId: '591916390428-8kq8ijgp2s4genp8089u0niau2mdji8s.apps.googleusercontent.com',
    iosBundleId: 'com.example.finApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBF__m92jpQ6O2ln-ohMtBVufjFP7M2xDQ',
    appId: '1:591916390428:ios:2f4ca12b84eb215cc3e7d9',
    messagingSenderId: '591916390428',
    projectId: 'financeapp-922c4',
    storageBucket: 'financeapp-922c4.appspot.com',
    iosClientId: '591916390428-8kq8ijgp2s4genp8089u0niau2mdji8s.apps.googleusercontent.com',
    iosBundleId: 'com.example.finApp',
  );
}
